# Generated by Django 5.0.6 on 2026-08-18 08:06

import django.db.models.deletion
import permits.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClearanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        default=permits.models.generate_reference_number,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("airline_operator", models.CharField(max_length=255)),
                ("aircraft_registration", models.CharField(max_length=100)),
                ("has_electronic_warfare", models.BooleanField(default=False)),
                ("electronic_warfare_details", models.TextField(blank=True, null=True)),
                ("has_aircraft_modifications", models.BooleanField(default=False)),
                (
                    "aircraft_modifications_details",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "clearance_category",
                    models.CharField(default="Overflight", max_length=100),
                ),
                ("clearance_type", models.CharField(default="Ad-Hoc", max_length=100)),
                ("purpose_of_flight", models.TextField()),
                ("aircraft_callsign", models.CharField(max_length=100)),
                ("pilot_in_command", models.CharField(max_length=150)),
                ("first_officer", models.CharField(max_length=150)),
                (
                    "entry_point",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("exit_point", models.CharField(blank=True, max_length=100, null=True)),
                ("flight_date", models.DateField(blank=True, null=True)),
                ("passengers_count", models.IntegerField(default=0)),
                ("cargo_details", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(
                        blank=True,
                        default="Clearance request submitted. Awaiting CAA automated verification.",
                    ),
                ),
                (
                    "issued_permit_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clearance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
