# Generated by Django 5.0.6 on 2026-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clearancerequest",
            name="attached_document_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clearancerequest",
            name="attached_document_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clearancerequest",
            name="response_notes",
            field=models.TextField(
                blank=True,
                default="Clearance request submitted. Awaiting CAA verification.",
            ),
        ),
    ]
